name: chore_master_local
services:
  chore_master_api:
    build:
      context: ../
      dockerfile: ./deployments/chore_master_api/Dockerfile
    environment:
      ENV: "local"
      SERVICE_NAME: "chore_master_api"
      COMPONENT_NAME: "web_server"
      MONGODB_URI: ${CHORE_MASTER_API_MONGODB_URI}
    ports:
      - 13000:13000
