name: chore_master_api_local
services:
  web_server:
    build:
      context: ../../../
      dockerfile: ./apps/chore_master_api/deployments/web_server/Dockerfile
    environment:
      ENV: "local"
      SERVICE_NAME: "chore_master_api"
      COMPONENT_NAME: "web_server"
      PORT: 8080
      DATABASE_ORIGIN: ${WEB_SERVER_DATABASE_ORIGIN}
      DATABASE_SCHEMA_NAME: ${WEB_SERVER_DATABASE_SCHEMA_NAME}
      CLOUDFLARE_TURNSTILE_SECRET_KEY: "1x0000000000000000000000000000000AA"
    ports:
      - 13000:8080
