@startuml chore_master_entities

!function $add($a)
!return "<color:#00ff00>" + $a + "</color>"
!endfunction

!function $remove($a)
!return "<color:#ff0000>" + $a + "</color>"
!endfunction

skinparam backgroundColor transparent
skinparam linetype ortho

package admin {
  entity "Organization" {
    * $add("reference: str <<PK>>")
    * $add("name: str")
  }

  entity "EndUser" {
    * $add("reference: str <<PK>>")
    * $add("organization_reference: str <<FK>>")
    * $add("name: str")
  }
}

package integration {
  entity "Resource" {
    * reference: str <<PK>>
    * $add("organization_reference: str <<FK>>")
    * $remove("end_user_reference: str <<FK>>")
    * discriminator: str = 'yahoo_finance_feed' $add("| 'node_manager'")
    * value: str
    --
    name: str
    $add("end_user_reference: str <<FK>>")
  }
}

package finance {
  entity "Asset" {
    * $remove("reference: str <<PK>>")
    * $remove("name: str")
    * $remove("symbol: str")
    * $remove("decimals: int")
    * $remove("is_settleable: bool")
  }

  entity "Instrument" {
    * $add("reference: str <<PK>>")
    * $add("name: str")
    * $add("symbol: str")
    * $add("quantity_decimals: int")
    * $add("price_decimals: int")
    * $add("is_settleable: bool")
    * $add("type: str = 'cash' | 'equity' | 'future' | 'option' | 'fixed_income'")
  }

  entity "Account" {
    * reference: str <<PK>>
    * $add("end_user_reference: str <<FK>>")
    * $remove("settlement_asset_reference: str <<FK>>")
    * $add("settlement_instrument_reference: str <<FK>>")
    * name: str
    * opened_time: datetime
    * ecosystem_type: str = 'TRAD_FI'
    --
    closed_time: datetime
  }

  entity "BalanceSheet" {
    * reference: str <<PK>>
    * $add("end_user_reference: str <<FK>>")
    * balanced_time: datetime
  }

  entity "BalanceEntry" {
    * reference: str <<PK>>
    * balance_sheet_reference: str <<FK>>
    * account_reference: str <<FK>>
    * amount: int
  }

  entity "Portfolio" {
    * $add("reference: str <<PK>>")
    * $add("end_user_reference: str <<FK>>")
    * $add("name: str")
    * $add("started_time: datetime")
    * $add("settlement_instrument_reference: str <<FK>>")
    --
    $add("description: str")
    $add("ended_time: datetime")
  }

  entity "Holding" { 
    * $add("reference: str <<PK>>")
    * $add("portfolio_reference: str <<FK>>")
    * $add("allocated_time: datetime")
  }

  entity "HoldingEntry" {
    * $add("reference: str <<PK>>")
    * $add("holding_reference: str <<FK>>")
    * $add("instrument_reference: str <<FK>>")
    * $add("quantity: int")
    * $add("average_cost_price: int")
  }

  entity "Settlement" {
    * $add("reference: str <<PK>>")
    * $add("portfolio_reference: str <<FK>>")
    * $add("settled_time: datetime")
    * $add("account_reference: str <<FK>>")
    * $add("quantity_change: int")
    * $add("instrument_reference: str <<FK>>")
  }
}

'Zero or One  |o--
'Exactly One  ||--
'Zero or Many }o--
'One or Many  }|--

Organization ||--o{ EndUser
Organization ||--o{ Resource

EndUser      ||--o{ Resource
EndUser      ||--o{ Account
EndUser      ||--o{ BalanceSheet
EndUser      ||--o{ Portfolio

BalanceSheet ||--o{ BalanceEntry: balance_entries
BalanceEntry }o--|| Account

Portfolio    }o--|| Instrument: settlement_instrument
Portfolio    }o--|{ Instrument: instruments
Portfolio    }o--o{ Holding: holdings
Portfolio    ||--o{ Settlement: settlements

Holding ||--o{ HoldingEntry: holding_entries
HoldingEntry }o--|| Instrument

@enduml