@startuml chore_master_entities

!function $add($a)
!return "<color:#87A96B>" + $a + "</color>"
!endfunction

!function $remove($a)
!return "<color:#BA0021>" + $a + "</color>"
!endfunction

skinparam backgroundColor transparent
skinparam linetype ortho

package identity {
  entity "UserGroup" {
    * $add("reference: str <<PK>>")
    * $add("name: str")
  }

  entity "User" {
    * $add("reference: str <<PK>>")
    * $add("user_group_reference: str <<FK>>")
    * $add("name: str")
  }
}

package integration {
  entity "Resource" {
    * reference: str <<PK>>
    * $add("user_group_reference: str <<FK>>")
    * $remove("end_user_reference: str <<FK>>")
    * discriminator: str \n = 'yahoo_finance_feed' $add("| 'node_manager'")
    * value: str
    --
    name: str
    $add("user_reference: str <<FK>>")
  }
}

package finance {
  entity "Account" {
    * reference: str <<PK>>
    * $add("user_reference: str <<FK>>")
    * settlement_asset_reference: str <<FK>>
    * name: str
    * opened_time: datetime
    * ecosystem_type: str = 'TRAD_FI'
    --
    closed_time: datetime
  }

  entity "BalanceSheet" {
    * reference: str <<PK>>
    * $add("user_reference: str <<FK>>")
    * balanced_time: datetime
  }

  entity "BalanceEntry" {
    * reference: str <<PK>>
    * balance_sheet_reference: str <<FK>>
    * account_reference: str <<FK>>
    * amount: int
  }

  entity "Portfolio" {
    * $add("reference: str <<PK>>")
    * $add("user_reference: str <<FK>>")
    * $add("name: str")
    --
    $add("description: str")
  }

  entity "Asset" {
    * reference: str <<PK>>
    * name: str
    * symbol: str
    * decimals: int
    * is_settleable: bool
  }

  entity "Instrument" {
    * $add("reference: str <<PK>>")
    * $add("name: str")
    * $add("quantity_decimals: int")
    * $add("price_decimals: int")
    * $add("instrument_type: str") \n $add(" = 'EQUITY' | 'FX' | 'EARNING'")
    --
    base_asset_reference: str <<FK>>
    quote_asset_reference: str <<FK>>
    settlement_asset_reference: str <<FK>>
    underlying_asset_reference: str <<FK>>
    staking_asset_reference: str <<FK>>
    yielding_asset_reference: str <<FK>>
  }

  entity "LedgerEntry" {
    * $add("reference: str <<PK>>")
    * $add("portfolio_reference: str <<FK>>")
    * $add("instrument_reference: str <<FK>>")
    * $add("entry_type: str") \n $add(" = 'BUY' | 'SELL'") \n $add(" | 'STAKE' | 'UNSTAKE'") \n $add(" | 'CASH_DIVIDEND' | 'STOCK_DIVIDEND'") \n $add(" | 'FUNDING_FEE' | 'INTEREST_DEDUCT'")
    * $add("source_type: str") \n $add(" = 'MANUAL' | 'MANAGED'")
    * $add("quantity: int")
    * $add("price: int")
    * $add("entry_time: datetime")
  }

  entity "FeeEntry" {
    * $add("reference: str <<PK>>")
    * $add("ledger_entry_reference: str <<FK>>")
    * $add("fee_type: str") \n $add(" = 'TRADE' | 'TAX' | 'GAS'")
    * $add("amount: int")
    * $add("asset_reference: str <<FK>>")
  }

  entity "IncomeStatementEntry" {
    * $add("portfolio_reference: str <<FK>>")
    * $add("entry_type: str") \n $add(" = 'CAPITAL_GAIN' | 'FEE'")
    * $add("amount: int")
    * $add("asset_reference: str <<FK>>")
    * $add("settled_time: datetime")
  }

  entity "Holding" {
    * $add("reference: str <<PK>>")
    * $add("portfolio_reference: str <<FK>>")
    * $add("held_time: datetime")
  }

  entity "HoldingEntry" { 
    * $add("reference: str <<PK>>")
    * $add("holding_reference: str <<FK>>")
    * $add("instrument_reference: str <<FK>>")
    * $add("quantity: int")
    * $add("average_cost_price: int")
  }
}

'Zero or One  |o--
'Exactly One  ||--
'Zero or Many }o--
'One or Many  }|--

UserGroup            ||--o{ User
UserGroup            ||--o{ Resource

User                 ||--o{ Resource
User                 ||--o{ Account
User                 ||--o{ BalanceSheet
User                 ||--o{ Portfolio

BalanceSheet         ||--o{ BalanceEntry: balance_entries
BalanceEntry         }o--|| Account

Portfolio            ||--o{ LedgerEntry: ledger_entries
Portfolio            ||--o{ IncomeStatementEntry: income_statement_entries
Portfolio            ||--o{ Holding: holdings

LedgerEntry          ||--o{ FeeEntry: fee_entries
LedgerEntry          }o--|| Instrument
Instrument           }o--o{ Asset: xxx_asset
FeeEntry             }o--|| Asset

IncomeStatementEntry }o--|| Asset

Holding              ||--o{ HoldingEntry: holding_entries
HoldingEntry         }o--|| Instrument

@enduml