@startuml chore_master_entities

!function $add($a)
!return "<color:#87A96B>" + $a + "</color>"
!endfunction

!function $remove($a)
!return "<color:#BA0021>" + $a + "</color>"
!endfunction

skinparam backgroundColor transparent
skinparam linetype ortho

package identity {
  entity "User" {
    * reference: str <<PK>>
    * name: str
    * username: str
    * password: str
  }

  entity "Role" {
    * reference: str <<PK>>
    * symbol: str
  }

  entity "UserRole" {
    * reference: str <<PK>>
    * user_reference: str <<FK>>
    * role_reference: str <<FK>>
  }

  entity "UserSession" {
    * reference: str <<PK>>
    * user_reference: str <<FK>>
    * user_agent: str
    * is_active: bool
    * expired_time: datetime
    --
    deactivated_time: datetime
  }
}

package integration {
  entity "Resource" {
    * reference: str <<PK>>
    * $remove("end_user_reference: str <<FK>>")
    * $add("user_reference: str <<FK>>")
    * discriminator: str \n = 'yahoo_finance_feed' $add("| 'node_manager'")
    * value: str
    --
    name: str
  }
}

package finance {
  entity "Account" {
    * reference: str <<PK>>
    * $add("user_reference: str <<FK>>")
    * settlement_asset_reference: str <<FK>>
    * name: str
    * opened_time: datetime
    * ecosystem_type: str = 'TRAD_FI'
    --
    closed_time: datetime
  }

  entity "BalanceSheet" {
    * reference: str <<PK>>
    * $add("user_reference: str <<FK>>")
    * balanced_time: datetime
  }

  entity "BalanceEntry" {
    * reference: str <<PK>>
    * balance_sheet_reference: str <<FK>>
    * account_reference: str <<FK>>
    * amount: int
  }

  entity "Portfolio" {
    * reference: str <<PK>>
    * user_reference: str <<FK>>
    * name: str
    --
    description: str
  }

  entity "Asset" {
    * reference: str <<PK>>
    * name: str
    * symbol: str
    * decimals: int
    * is_settleable: bool
  }

  entity "Instrument" {
    * reference: str <<PK>>
    * name: str
    * quantity_decimals: int
    * price_decimals: int
    * instrument_type: str \n = 'EQUITY' | 'FX' | 'EARNING'
    --
    base_asset_reference: str <<FK>>
    quote_asset_reference: str <<FK>>
    settlement_asset_reference: str <<FK>>
    underlying_asset_reference: str <<FK>>
    staking_asset_reference: str <<FK>>
    yielding_asset_reference: str <<FK>>
  }

  entity "LedgerEntry" {
    * reference: str <<PK>>
    * portfolio_reference: str <<FK>>
    * instrument_reference: str <<FK>>
    * entry_type: str \n = 'BUY' | 'SELL' \n | 'STAKE' | 'UNSTAKE' \n | 'CASH_DIVIDEND' | 'STOCK_DIVIDEND' \n | 'FUNDING_FEE' | 'INTEREST'
    * source_type: str \n = 'MANUAL' | 'MANAGED'
    * quantity: int
    * price: int
    * entry_time: datetime
  }

  entity "FeeEntry" {
    * reference: str <<PK>>
    * ledger_entry_reference: str <<FK>>
    * fee_type: str \n = 'TRADE' | 'TAX' | 'GAS'
    * amount: int
    * asset_reference: str <<FK>>
  }

  entity "IncomeStatementEntry" {
    * $add("reference: str <<PK>>")
    * $add("portfolio_reference: str <<FK>>")
    * $add("entry_type: str") \n $add(" = 'CAPITAL_GAIN'") \n $add(" | 'CASH_DIVIDEND'") \n $add(" | 'STAKING_YIELD'") \n $add(" | 'FUNDING_FEE'") \n $add(" | 'TRADE_FEE' | 'TAX_FEE' | 'GAS_FEE'")
    * $add("amount: int")
    * $add("asset_reference: str <<FK>>")
    * $add("settled_time: datetime")
  }

  entity "Holding" {
    * $add("reference: str <<PK>>")
    * $add("portfolio_reference: str <<FK>>")
    * $add("held_time: datetime")
  }

  entity "HoldingEntry" { 
    * $add("reference: str <<PK>>")
    * $add("holding_reference: str <<FK>>")
    * $add("instrument_reference: str <<FK>>")
    * $add("quantity: int")
    * $add("average_cost_price: int")
  }
}

'Zero or One  |o--
'Exactly One  ||--
'Zero or Many }o--
'One or Many  }|--

User                 ||--o{ UserRole
User                 ||--o{ UserSession
User                 ||--o{ Resource
User                 ||--o{ Account
User                 ||--o{ BalanceSheet
User                 ||--o{ Portfolio
UserRole             }o--|| Role

BalanceSheet         ||--o{ BalanceEntry: balance_entries
BalanceEntry         }o--|| Account

Account              }o--|| Asset: settlement_asset

Portfolio            ||--o{ LedgerEntry: ledger_entries
Portfolio            ||--o{ IncomeStatementEntry: income_statement_entries
Portfolio            ||--o{ Holding: holdings

LedgerEntry          ||--o{ FeeEntry: fee_entries
LedgerEntry          }o--|| Instrument
Instrument           }o--o{ Asset: xxx_asset
FeeEntry             }o--|| Asset

IncomeStatementEntry }o--|| Asset

Holding              ||--o{ HoldingEntry: holding_entries
HoldingEntry         }o--|| Instrument

@enduml