"""empty message

Revision ID: ec6dae9f4768
Revises: f23174f1565e
Create Date: 2024-09-01 20:47:27.804086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6dae9f4768'
down_revision = 'f23174f1565e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_management_account',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_account'))
    )
    op.create_index(op.f('ix_financial_management_account_created_time'), 'financial_management_account', ['created_time'], unique=False)
    op.create_index(op.f('ix_financial_management_account_reference'), 'financial_management_account', ['reference'], unique=False)
    op.create_index(op.f('ix_financial_management_account_updated_time'), 'financial_management_account', ['updated_time'], unique=False)
    op.create_table('financial_management_asset',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_asset'))
    )
    op.create_index(op.f('ix_financial_management_asset_created_time'), 'financial_management_asset', ['created_time'], unique=False)
    op.create_index(op.f('ix_financial_management_asset_reference'), 'financial_management_asset', ['reference'], unique=False)
    op.create_index(op.f('ix_financial_management_asset_updated_time'), 'financial_management_asset', ['updated_time'], unique=False)
    op.create_table('financial_management_bill',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('accounting_type', sa.String(), nullable=False),
    sa.Column('amount_change', sa.DECIMAL(precision=16, scale=40), nullable=False),
    sa.Column('asset_reference', sa.String(), nullable=False),
    sa.Column('order_reference', sa.String(), nullable=True),
    sa.Column('billed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_bill'))
    )
    op.create_index(op.f('ix_financial_management_bill_created_time'), 'financial_management_bill', ['created_time'], unique=False)
    op.create_index(op.f('ix_financial_management_bill_reference'), 'financial_management_bill', ['reference'], unique=False)
    op.create_index(op.f('ix_financial_management_bill_updated_time'), 'financial_management_bill', ['updated_time'], unique=False)
    op.create_table('financial_management_net_value',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=16, scale=40), nullable=False),
    sa.Column('settlement_asset_reference', sa.String(), nullable=False),
    sa.Column('settled_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_net_value'))
    )
    op.create_index(op.f('ix_financial_management_net_value_created_time'), 'financial_management_net_value', ['created_time'], unique=False)
    op.create_index(op.f('ix_financial_management_net_value_reference'), 'financial_management_net_value', ['reference'], unique=False)
    op.create_index(op.f('ix_financial_management_net_value_updated_time'), 'financial_management_net_value', ['updated_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_management_net_value_updated_time'), table_name='financial_management_net_value')
    op.drop_index(op.f('ix_financial_management_net_value_reference'), table_name='financial_management_net_value')
    op.drop_index(op.f('ix_financial_management_net_value_created_time'), table_name='financial_management_net_value')
    op.drop_table('financial_management_net_value')
    op.drop_index(op.f('ix_financial_management_bill_updated_time'), table_name='financial_management_bill')
    op.drop_index(op.f('ix_financial_management_bill_reference'), table_name='financial_management_bill')
    op.drop_index(op.f('ix_financial_management_bill_created_time'), table_name='financial_management_bill')
    op.drop_table('financial_management_bill')
    op.drop_index(op.f('ix_financial_management_asset_updated_time'), table_name='financial_management_asset')
    op.drop_index(op.f('ix_financial_management_asset_reference'), table_name='financial_management_asset')
    op.drop_index(op.f('ix_financial_management_asset_created_time'), table_name='financial_management_asset')
    op.drop_table('financial_management_asset')
    op.drop_index(op.f('ix_financial_management_account_updated_time'), table_name='financial_management_account')
    op.drop_index(op.f('ix_financial_management_account_reference'), table_name='financial_management_account')
    op.drop_index(op.f('ix_financial_management_account_created_time'), table_name='financial_management_account')
    op.drop_table('financial_management_account')
    # ### end Alembic commands ###
