"""empty message

Revision ID: f23174f1565e
Revises: 
Create Date: 2024-09-01 16:12:50.272502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23174f1565e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('some_module_some_entity',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('a', sa.Boolean(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('d', sa.DECIMAL(precision=16, scale=40), nullable=False),
    sa.Column('e', sa.String(), nullable=False),
    sa.Column('f', sa.DateTime(), nullable=False),
    sa.Column('g', sa.String(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('i', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_some_module_some_entity'))
    )
    op.create_index(op.f('ix_some_module_some_entity_created_time'), 'some_module_some_entity', ['created_time'], unique=False)
    op.create_index(op.f('ix_some_module_some_entity_reference'), 'some_module_some_entity', ['reference'], unique=False)
    op.create_index(op.f('ix_some_module_some_entity_updated_time'), 'some_module_some_entity', ['updated_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_some_module_some_entity_updated_time'), table_name='some_module_some_entity')
    op.drop_index(op.f('ix_some_module_some_entity_reference'), table_name='some_module_some_entity')
    op.drop_index(op.f('ix_some_module_some_entity_created_time'), table_name='some_module_some_entity')
    op.drop_table('some_module_some_entity')
    # ### end Alembic commands ###
