"""empty message

Revision ID: a6d6ff189689
Revises: ec6dae9f4768
Create Date: 2024-09-05 20:54:43.832636

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6d6ff189689'
down_revision = 'ec6dae9f4768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_financial_management_account_created_time', table_name='financial_management_account')
    op.drop_index('ix_financial_management_account_reference', table_name='financial_management_account')
    op.drop_index('ix_financial_management_account_updated_time', table_name='financial_management_account')
    op.create_index(op.f('ix_public_public_financial_management_account_created_time'), 'financial_management_account', ['created_time'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_account_reference'), 'financial_management_account', ['reference'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_account_updated_time'), 'financial_management_account', ['updated_time'], unique=False, schema='public')
    op.drop_index('ix_financial_management_asset_created_time', table_name='financial_management_asset')
    op.drop_index('ix_financial_management_asset_reference', table_name='financial_management_asset')
    op.drop_index('ix_financial_management_asset_updated_time', table_name='financial_management_asset')
    op.create_index(op.f('ix_public_public_financial_management_asset_created_time'), 'financial_management_asset', ['created_time'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_asset_reference'), 'financial_management_asset', ['reference'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_asset_updated_time'), 'financial_management_asset', ['updated_time'], unique=False, schema='public')
    op.alter_column('financial_management_bill', 'amount_change',
               existing_type=sa.NUMERIC(precision=16, scale=40),
               type_=sa.DECIMAL(precision=56, scale=40),
               existing_nullable=False)
    op.drop_index('ix_financial_management_bill_created_time', table_name='financial_management_bill')
    op.drop_index('ix_financial_management_bill_reference', table_name='financial_management_bill')
    op.drop_index('ix_financial_management_bill_updated_time', table_name='financial_management_bill')
    op.create_index(op.f('ix_public_public_financial_management_bill_created_time'), 'financial_management_bill', ['created_time'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_bill_reference'), 'financial_management_bill', ['reference'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_bill_updated_time'), 'financial_management_bill', ['updated_time'], unique=False, schema='public')
    op.alter_column('financial_management_net_value', 'amount',
               existing_type=sa.NUMERIC(precision=16, scale=40),
               type_=sa.DECIMAL(precision=56, scale=40),
               existing_nullable=False)
    op.drop_index('ix_financial_management_net_value_created_time', table_name='financial_management_net_value')
    op.drop_index('ix_financial_management_net_value_reference', table_name='financial_management_net_value')
    op.drop_index('ix_financial_management_net_value_updated_time', table_name='financial_management_net_value')
    op.create_index(op.f('ix_public_public_financial_management_net_value_created_time'), 'financial_management_net_value', ['created_time'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_net_value_reference'), 'financial_management_net_value', ['reference'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_financial_management_net_value_updated_time'), 'financial_management_net_value', ['updated_time'], unique=False, schema='public')
    op.alter_column('some_module_some_entity', 'd',
               existing_type=sa.NUMERIC(precision=16, scale=40),
               type_=sa.DECIMAL(precision=56, scale=40),
               existing_nullable=False)
    op.drop_index('ix_some_module_some_entity_created_time', table_name='some_module_some_entity')
    op.drop_index('ix_some_module_some_entity_reference', table_name='some_module_some_entity')
    op.drop_index('ix_some_module_some_entity_updated_time', table_name='some_module_some_entity')
    op.create_index(op.f('ix_public_public_some_module_some_entity_created_time'), 'some_module_some_entity', ['created_time'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_some_module_some_entity_reference'), 'some_module_some_entity', ['reference'], unique=False, schema='public')
    op.create_index(op.f('ix_public_public_some_module_some_entity_updated_time'), 'some_module_some_entity', ['updated_time'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_public_some_module_some_entity_updated_time'), table_name='some_module_some_entity', schema='public')
    op.drop_index(op.f('ix_public_public_some_module_some_entity_reference'), table_name='some_module_some_entity', schema='public')
    op.drop_index(op.f('ix_public_public_some_module_some_entity_created_time'), table_name='some_module_some_entity', schema='public')
    op.create_index('ix_some_module_some_entity_updated_time', 'some_module_some_entity', ['updated_time'], unique=False)
    op.create_index('ix_some_module_some_entity_reference', 'some_module_some_entity', ['reference'], unique=False)
    op.create_index('ix_some_module_some_entity_created_time', 'some_module_some_entity', ['created_time'], unique=False)
    op.alter_column('some_module_some_entity', 'd',
               existing_type=sa.DECIMAL(precision=56, scale=40),
               type_=sa.NUMERIC(precision=16, scale=40),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_public_financial_management_net_value_updated_time'), table_name='financial_management_net_value', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_net_value_reference'), table_name='financial_management_net_value', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_net_value_created_time'), table_name='financial_management_net_value', schema='public')
    op.create_index('ix_financial_management_net_value_updated_time', 'financial_management_net_value', ['updated_time'], unique=False)
    op.create_index('ix_financial_management_net_value_reference', 'financial_management_net_value', ['reference'], unique=False)
    op.create_index('ix_financial_management_net_value_created_time', 'financial_management_net_value', ['created_time'], unique=False)
    op.alter_column('financial_management_net_value', 'amount',
               existing_type=sa.DECIMAL(precision=56, scale=40),
               type_=sa.NUMERIC(precision=16, scale=40),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_public_financial_management_bill_updated_time'), table_name='financial_management_bill', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_bill_reference'), table_name='financial_management_bill', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_bill_created_time'), table_name='financial_management_bill', schema='public')
    op.create_index('ix_financial_management_bill_updated_time', 'financial_management_bill', ['updated_time'], unique=False)
    op.create_index('ix_financial_management_bill_reference', 'financial_management_bill', ['reference'], unique=False)
    op.create_index('ix_financial_management_bill_created_time', 'financial_management_bill', ['created_time'], unique=False)
    op.alter_column('financial_management_bill', 'amount_change',
               existing_type=sa.DECIMAL(precision=56, scale=40),
               type_=sa.NUMERIC(precision=16, scale=40),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_public_financial_management_asset_updated_time'), table_name='financial_management_asset', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_asset_reference'), table_name='financial_management_asset', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_asset_created_time'), table_name='financial_management_asset', schema='public')
    op.create_index('ix_financial_management_asset_updated_time', 'financial_management_asset', ['updated_time'], unique=False)
    op.create_index('ix_financial_management_asset_reference', 'financial_management_asset', ['reference'], unique=False)
    op.create_index('ix_financial_management_asset_created_time', 'financial_management_asset', ['created_time'], unique=False)
    op.drop_index(op.f('ix_public_public_financial_management_account_updated_time'), table_name='financial_management_account', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_account_reference'), table_name='financial_management_account', schema='public')
    op.drop_index(op.f('ix_public_public_financial_management_account_created_time'), table_name='financial_management_account', schema='public')
    op.create_index('ix_financial_management_account_updated_time', 'financial_management_account', ['updated_time'], unique=False)
    op.create_index('ix_financial_management_account_reference', 'financial_management_account', ['reference'], unique=False)
    op.create_index('ix_financial_management_account_created_time', 'financial_management_account', ['created_time'], unique=False)
    # ### end Alembic commands ###
