"""empty message

Revision ID: 857270708e5a
Revises: f46a1ec0f608
Create Date: 2025-03-22 22:49:17.994855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857270708e5a'
down_revision = 'f46a1ec0f608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_fee_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_change', sa.Integer(), nullable=False))
        batch_op.drop_column('amount')

    with op.batch_alter_table('finance_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('px_decimals', sa.Integer(), nullable=False))
        batch_op.drop_column('price_decimals')

    with op.batch_alter_table('finance_ledger_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_amount_change', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('settlement_asset_reference', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('quantity_change', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fill_px', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))
        batch_op.alter_column('instrument_reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('quantity')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_ledger_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.alter_column('instrument_reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('remark')
        batch_op.drop_column('fill_px')
        batch_op.drop_column('quantity_change')
        batch_op.drop_column('settlement_asset_reference')
        batch_op.drop_column('settlement_amount_change')

    with op.batch_alter_table('finance_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_decimals', sa.INTEGER(), nullable=False))
        batch_op.drop_column('px_decimals')

    with op.batch_alter_table('finance_fee_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False))
        batch_op.drop_column('amount_change')

    # ### end Alembic commands ###
