"""empty message

Revision ID: 1b70193a0dc6
Revises: 
Create Date: 2025-03-10 23:32:06.144373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b70193a0dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_account',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('opened_time', sa.DateTime(), nullable=False),
    sa.Column('closed_time', sa.DateTime(), nullable=True),
    sa.Column('ecosystem_type', sa.String(), nullable=False),
    sa.Column('settlement_asset_reference', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_account'))
    )
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_account_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_account_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_account_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_asset',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_settleable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_asset'))
    )
    with op.batch_alter_table('finance_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_asset_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_asset_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_asset_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_balance_entry',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('balance_sheet_reference', sa.String(), nullable=False),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_balance_entry'))
    )
    with op.batch_alter_table('finance_balance_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_balance_entry_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_entry_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_entry_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_balance_sheet',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('balanced_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_balance_sheet'))
    )
    with op.batch_alter_table('finance_balance_sheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_balance_sheet_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_sheet_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_sheet_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_fee_entry',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ledger_entry_reference', sa.String(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('asset_reference', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_fee_entry'))
    )
    with op.batch_alter_table('finance_fee_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_fee_entry_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_fee_entry_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_fee_entry_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_instrument',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity_decimals', sa.Integer(), nullable=False),
    sa.Column('price_decimals', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('base_asset_reference', sa.String(), nullable=True),
    sa.Column('quote_asset_reference', sa.String(), nullable=True),
    sa.Column('settlement_asset_reference', sa.String(), nullable=True),
    sa.Column('underlying_asset_reference', sa.String(), nullable=True),
    sa.Column('staking_asset_reference', sa.String(), nullable=True),
    sa.Column('yielding_asset_reference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_instrument'))
    )
    with op.batch_alter_table('finance_instrument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_instrument_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_instrument_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_instrument_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_ledger_entry',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('portfolio_reference', sa.String(), nullable=False),
    sa.Column('instrument_reference', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_ledger_entry'))
    )
    with op.batch_alter_table('finance_ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_ledger_entry_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_ledger_entry_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_ledger_entry_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_portfolio',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_portfolio'))
    )
    with op.batch_alter_table('finance_portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_portfolio_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_portfolio_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_portfolio_updated_time'), ['updated_time'], unique=False)

    op.create_table('identity_user',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_identity_user'))
    )
    with op.batch_alter_table('identity_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_user_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_updated_time'), ['updated_time'], unique=False)

    op.create_table('identity_user_session',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reference', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expired_time', sa.DateTime(), nullable=False),
    sa.Column('deactivated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_identity_user_session'))
    )
    with op.batch_alter_table('identity_user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_user_session_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_session_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_session_updated_time'), ['updated_time'], unique=False)

    op.create_table('integration_resource',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_user_reference', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discriminator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_integration_resource'))
    )
    with op.batch_alter_table('integration_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_resource_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_updated_time'), ['updated_time'], unique=False)

    op.create_table('some_module_some_entity',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('a', sa.Boolean(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('d', sa.DECIMAL(precision=50, scale=18), nullable=False),
    sa.Column('e', sa.String(), nullable=False),
    sa.Column('f', sa.DateTime(), nullable=False),
    sa.Column('g', sa.String(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('i', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_some_module_some_entity'))
    )
    with op.batch_alter_table('some_module_some_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_some_module_some_entity_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_some_module_some_entity_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_some_module_some_entity_updated_time'), ['updated_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('some_module_some_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_some_module_some_entity_updated_time'))
        batch_op.drop_index(batch_op.f('ix_some_module_some_entity_reference'))
        batch_op.drop_index(batch_op.f('ix_some_module_some_entity_created_time'))

    op.drop_table('some_module_some_entity')
    with op.batch_alter_table('integration_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_resource_updated_time'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_reference'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_created_time'))

    op.drop_table('integration_resource')
    with op.batch_alter_table('identity_user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_user_session_updated_time'))
        batch_op.drop_index(batch_op.f('ix_identity_user_session_reference'))
        batch_op.drop_index(batch_op.f('ix_identity_user_session_created_time'))

    op.drop_table('identity_user_session')
    with op.batch_alter_table('identity_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_user_updated_time'))
        batch_op.drop_index(batch_op.f('ix_identity_user_reference'))
        batch_op.drop_index(batch_op.f('ix_identity_user_created_time'))

    op.drop_table('identity_user')
    with op.batch_alter_table('finance_portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_portfolio_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_portfolio_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_portfolio_created_time'))

    op.drop_table('finance_portfolio')
    with op.batch_alter_table('finance_ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_ledger_entry_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_ledger_entry_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_ledger_entry_created_time'))

    op.drop_table('finance_ledger_entry')
    with op.batch_alter_table('finance_instrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_instrument_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_instrument_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_instrument_created_time'))

    op.drop_table('finance_instrument')
    with op.batch_alter_table('finance_fee_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_fee_entry_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_fee_entry_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_fee_entry_created_time'))

    op.drop_table('finance_fee_entry')
    with op.batch_alter_table('finance_balance_sheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_balance_sheet_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_sheet_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_sheet_created_time'))

    op.drop_table('finance_balance_sheet')
    with op.batch_alter_table('finance_balance_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_balance_entry_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_entry_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_entry_created_time'))

    op.drop_table('finance_balance_entry')
    with op.batch_alter_table('finance_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_asset_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_asset_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_asset_created_time'))

    op.drop_table('finance_asset')
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_account_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_account_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_account_created_time'))

    op.drop_table('finance_account')
    # ### end Alembic commands ###
