"""empty message

Revision ID: 82817098d2b2
Revises: ec75cc1e769d
Create Date: 2025-04-22 12:05:39.873318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82817098d2b2'
down_revision = 'ec75cc1e769d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.drop_column('ecosystem_type')

    with op.batch_alter_table('finance_balance_entry', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_balance_entry', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecosystem_type', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
