"""empty message

Revision ID: 1e1af3f788ee
Revises: f46a1ec0f608
Create Date: 2025-03-23 21:33:17.735448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1af3f788ee'
down_revision = 'f46a1ec0f608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_fee_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_finance_fee_entry_created_time')
        batch_op.drop_index('ix_finance_fee_entry_reference')
        batch_op.drop_index('ix_finance_fee_entry_updated_time')

    op.drop_table('finance_fee_entry')
    with op.batch_alter_table('finance_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('px_decimals', sa.Integer(), nullable=False))
        batch_op.drop_column('price_decimals')

    with op.batch_alter_table('finance_ledger_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_amount_change', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('settlement_asset_reference', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('parent_ledger_entry_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quantity_change', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fill_px', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))
        batch_op.alter_column('instrument_reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_ledger_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=False))
        batch_op.alter_column('instrument_reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('remark')
        batch_op.drop_column('fill_px')
        batch_op.drop_column('quantity_change')
        batch_op.drop_column('parent_ledger_entry_reference')
        batch_op.drop_column('settlement_asset_reference')
        batch_op.drop_column('settlement_amount_change')

    with op.batch_alter_table('finance_instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_decimals', sa.INTEGER(), nullable=False))
        batch_op.drop_column('px_decimals')

    op.create_table('finance_fee_entry',
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ledger_entry_reference', sa.VARCHAR(), nullable=False),
    sa.Column('fee_type', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('asset_reference', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name='pk_finance_fee_entry')
    )
    with op.batch_alter_table('finance_fee_entry', schema=None) as batch_op:
        batch_op.create_index('ix_finance_fee_entry_updated_time', ['updated_time'], unique=False)
        batch_op.create_index('ix_finance_fee_entry_reference', ['reference'], unique=False)
        batch_op.create_index('ix_finance_fee_entry_created_time', ['created_time'], unique=False)

    # ### end Alembic commands ###
