"""empty message

Revision ID: 36f00d0d3481
Revises: ef4354e0a1b6
Create Date: 2025-05-14 16:42:46.388921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f00d0d3481'
down_revision = 'ef4354e0a1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
