"""empty message

Revision ID: 3b0f77ce2430
Revises: fa1f402c97c7
Create Date: 2025-02-24 01:29:56.775102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0f77ce2430'
down_revision = 'fa1f402c97c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_account',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('opened_time', sa.DateTime(), nullable=False),
    sa.Column('closed_time', sa.DateTime(), nullable=True),
    sa.Column('ecosystem_type', sa.String(), nullable=False),
    sa.Column('settlement_asset_reference', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_account'))
    )
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_account_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_account_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_account_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_asset',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_settleable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_asset'))
    )
    with op.batch_alter_table('finance_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_asset_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_asset_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_asset_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_balance_entry',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('balance_sheet_reference', sa.String(), nullable=False),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_balance_entry'))
    )
    with op.batch_alter_table('finance_balance_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_balance_entry_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_entry_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_entry_updated_time'), ['updated_time'], unique=False)

    op.create_table('finance_balance_sheet',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('balanced_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_balance_sheet'))
    )
    with op.batch_alter_table('finance_balance_sheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_balance_sheet_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_sheet_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_balance_sheet_updated_time'), ['updated_time'], unique=False)

    op.create_table('integration_resource',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_user_reference', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discriminator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_integration_resource'))
    )
    with op.batch_alter_table('integration_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_resource_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_resource_updated_time'), ['updated_time'], unique=False)

    with op.batch_alter_table('financial_management_account', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_management_account_created_time')
        batch_op.drop_index('ix_financial_management_account_reference')
        batch_op.drop_index('ix_financial_management_account_updated_time')

    op.drop_table('financial_management_account')
    with op.batch_alter_table('financial_management_net_value', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_management_net_value_created_time')
        batch_op.drop_index('ix_financial_management_net_value_reference')
        batch_op.drop_index('ix_financial_management_net_value_updated_time')

    op.drop_table('financial_management_net_value')
    with op.batch_alter_table('financial_management_asset', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_management_asset_created_time')
        batch_op.drop_index('ix_financial_management_asset_reference')
        batch_op.drop_index('ix_financial_management_asset_updated_time')

    op.drop_table('financial_management_asset')
    with op.batch_alter_table('financial_management_bill', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_management_bill_created_time')
        batch_op.drop_index('ix_financial_management_bill_reference')
        batch_op.drop_index('ix_financial_management_bill_updated_time')

    op.drop_table('financial_management_bill')
    with op.batch_alter_table('some_module_some_entity', schema=None) as batch_op:
        batch_op.alter_column('d',
               existing_type=sa.DECIMAL(precision=56, scale=40),
               type_=sa.DECIMAL(precision=50, scale=18),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('some_module_some_entity', schema=None) as batch_op:
        batch_op.alter_column('d',
               existing_type=sa.DECIMAL(precision=50, scale=18),
               type_=sa.DECIMAL(precision=56, scale=40),
               existing_nullable=False)

    op.create_table('financial_management_bill',
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('account_reference', sa.VARCHAR(), nullable=False),
    sa.Column('business_type', sa.VARCHAR(), nullable=False),
    sa.Column('accounting_type', sa.VARCHAR(), nullable=False),
    sa.Column('amount_change', sa.DECIMAL(precision=56, scale=40), nullable=False),
    sa.Column('asset_reference', sa.VARCHAR(), nullable=False),
    sa.Column('order_reference', sa.VARCHAR(), nullable=True),
    sa.Column('billed_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name='pk_financial_management_bill')
    )
    with op.batch_alter_table('financial_management_bill', schema=None) as batch_op:
        batch_op.create_index('ix_financial_management_bill_updated_time', ['updated_time'], unique=False)
        batch_op.create_index('ix_financial_management_bill_reference', ['reference'], unique=False)
        batch_op.create_index('ix_financial_management_bill_created_time', ['created_time'], unique=False)

    op.create_table('financial_management_asset',
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name='pk_financial_management_asset')
    )
    with op.batch_alter_table('financial_management_asset', schema=None) as batch_op:
        batch_op.create_index('ix_financial_management_asset_updated_time', ['updated_time'], unique=False)
        batch_op.create_index('ix_financial_management_asset_reference', ['reference'], unique=False)
        batch_op.create_index('ix_financial_management_asset_created_time', ['created_time'], unique=False)

    op.create_table('financial_management_net_value',
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('account_reference', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=56, scale=40), nullable=False),
    sa.Column('settlement_asset_reference', sa.VARCHAR(), nullable=False),
    sa.Column('settled_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name='pk_financial_management_net_value')
    )
    with op.batch_alter_table('financial_management_net_value', schema=None) as batch_op:
        batch_op.create_index('ix_financial_management_net_value_updated_time', ['updated_time'], unique=False)
        batch_op.create_index('ix_financial_management_net_value_reference', ['reference'], unique=False)
        batch_op.create_index('ix_financial_management_net_value_created_time', ['created_time'], unique=False)

    op.create_table('financial_management_account',
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name='pk_financial_management_account')
    )
    with op.batch_alter_table('financial_management_account', schema=None) as batch_op:
        batch_op.create_index('ix_financial_management_account_updated_time', ['updated_time'], unique=False)
        batch_op.create_index('ix_financial_management_account_reference', ['reference'], unique=False)
        batch_op.create_index('ix_financial_management_account_created_time', ['created_time'], unique=False)

    with op.batch_alter_table('integration_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_resource_updated_time'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_reference'))
        batch_op.drop_index(batch_op.f('ix_integration_resource_created_time'))

    op.drop_table('integration_resource')
    with op.batch_alter_table('finance_balance_sheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_balance_sheet_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_sheet_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_sheet_created_time'))

    op.drop_table('finance_balance_sheet')
    with op.batch_alter_table('finance_balance_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_balance_entry_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_entry_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_balance_entry_created_time'))

    op.drop_table('finance_balance_entry')
    with op.batch_alter_table('finance_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_asset_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_asset_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_asset_created_time'))

    op.drop_table('finance_asset')
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_account_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_account_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_account_created_time'))

    op.drop_table('finance_account')
    # ### end Alembic commands ###
