"""empty message

Revision ID: 988ca8b8c47b
Revises: ec75cc1e769d
Create Date: 2025-04-21 15:38:51.666587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988ca8b8c47b'
down_revision = 'ec75cc1e769d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.drop_column('ecosystem_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecosystem_type', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
