"""empty message

Revision ID: fa1f402c97c7
Revises: 
Create Date: 2025-02-08 11:47:52.889310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1f402c97c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_management_account',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_account'))
    )
    with op.batch_alter_table('financial_management_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_management_account_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_account_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_account_updated_time'), ['updated_time'], unique=False)

    op.create_table('financial_management_asset',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_asset'))
    )
    with op.batch_alter_table('financial_management_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_management_asset_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_asset_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_asset_updated_time'), ['updated_time'], unique=False)

    op.create_table('financial_management_bill',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('accounting_type', sa.String(), nullable=False),
    sa.Column('amount_change', sa.DECIMAL(precision=50, scale=18), nullable=False),
    sa.Column('asset_reference', sa.String(), nullable=False),
    sa.Column('order_reference', sa.String(), nullable=True),
    sa.Column('billed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_bill'))
    )
    with op.batch_alter_table('financial_management_bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_management_bill_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_bill_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_bill_updated_time'), ['updated_time'], unique=False)

    op.create_table('financial_management_net_value',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('account_reference', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=50, scale=18), nullable=False),
    sa.Column('settlement_asset_reference', sa.String(), nullable=False),
    sa.Column('settled_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_financial_management_net_value'))
    )
    with op.batch_alter_table('financial_management_net_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_management_net_value_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_net_value_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_management_net_value_updated_time'), ['updated_time'], unique=False)

    op.create_table('some_module_some_entity',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('a', sa.Boolean(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('d', sa.DECIMAL(precision=50, scale=18), nullable=False),
    sa.Column('e', sa.String(), nullable=False),
    sa.Column('f', sa.DateTime(), nullable=False),
    sa.Column('g', sa.String(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('i', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_some_module_some_entity'))
    )
    with op.batch_alter_table('some_module_some_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_some_module_some_entity_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_some_module_some_entity_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_some_module_some_entity_updated_time'), ['updated_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('some_module_some_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_some_module_some_entity_updated_time'))
        batch_op.drop_index(batch_op.f('ix_some_module_some_entity_reference'))
        batch_op.drop_index(batch_op.f('ix_some_module_some_entity_created_time'))

    op.drop_table('some_module_some_entity')
    with op.batch_alter_table('financial_management_net_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_management_net_value_updated_time'))
        batch_op.drop_index(batch_op.f('ix_financial_management_net_value_reference'))
        batch_op.drop_index(batch_op.f('ix_financial_management_net_value_created_time'))

    op.drop_table('financial_management_net_value')
    with op.batch_alter_table('financial_management_bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_management_bill_updated_time'))
        batch_op.drop_index(batch_op.f('ix_financial_management_bill_reference'))
        batch_op.drop_index(batch_op.f('ix_financial_management_bill_created_time'))

    op.drop_table('financial_management_bill')
    with op.batch_alter_table('financial_management_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_management_asset_updated_time'))
        batch_op.drop_index(batch_op.f('ix_financial_management_asset_reference'))
        batch_op.drop_index(batch_op.f('ix_financial_management_asset_created_time'))

    op.drop_table('financial_management_asset')
    with op.batch_alter_table('financial_management_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_management_account_updated_time'))
        batch_op.drop_index(batch_op.f('ix_financial_management_account_reference'))
        batch_op.drop_index(batch_op.f('ix_financial_management_account_created_time'))

    op.drop_table('financial_management_account')
    # ### end Alembic commands ###
