"""empty message

Revision ID: c414fe70c199
Revises: f16adeae2198
Create Date: 2025-03-13 17:21:40.377669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c414fe70c199'
down_revision = 'f16adeae2198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_operator',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reference', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discriminator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_integration_operator'))
    )
    with op.batch_alter_table('integration_operator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_operator_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_operator_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_operator_updated_time'), ['updated_time'], unique=False)

    with op.batch_alter_table('integration_resource', schema=None) as batch_op:
        batch_op.drop_index('ix_integration_resource_created_time')
        batch_op.drop_index('ix_integration_resource_reference')
        batch_op.drop_index('ix_integration_resource_updated_time')

    op.drop_table('integration_resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_resource',
    sa.Column('reference', sa.VARCHAR(), nullable=False),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reference', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('discriminator', sa.VARCHAR(), nullable=False),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name='pk_integration_resource')
    )
    with op.batch_alter_table('integration_resource', schema=None) as batch_op:
        batch_op.create_index('ix_integration_resource_updated_time', ['updated_time'], unique=False)
        batch_op.create_index('ix_integration_resource_reference', ['reference'], unique=False)
        batch_op.create_index('ix_integration_resource_created_time', ['created_time'], unique=False)

    with op.batch_alter_table('integration_operator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_operator_updated_time'))
        batch_op.drop_index(batch_op.f('ix_integration_operator_reference'))
        batch_op.drop_index(batch_op.f('ix_integration_operator_created_time'))

    op.drop_table('integration_operator')
    # ### end Alembic commands ###
