"""empty message

Revision ID: 1c2ce779b9cb
Revises: c4c713812503
Create Date: 2025-05-15 20:35:38.683046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2ce779b9cb'
down_revision = 'c4c713812503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_user_attribute',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reference', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_identity_user_attribute'))
    )
    with op.batch_alter_table('identity_user_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_user_attribute_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_attribute_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_user_attribute_updated_time'), ['updated_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_user_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_user_attribute_updated_time'))
        batch_op.drop_index(batch_op.f('ix_identity_user_attribute_reference'))
        batch_op.drop_index(batch_op.f('ix_identity_user_attribute_created_time'))

    op.drop_table('identity_user_attribute')
    # ### end Alembic commands ###
