"""empty message

Revision ID: ef4354e0a1b6
Revises: 82817098d2b2
Create Date: 2025-05-08 17:30:57.217490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4354e0a1b6'
down_revision = '82817098d2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_price',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reference', sa.String(), nullable=False),
    sa.Column('base_asset_reference', sa.String(), nullable=False),
    sa.Column('quote_asset_reference', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confirmed_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_finance_price'))
    )
    with op.batch_alter_table('finance_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_price_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_price_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_price_updated_time'), ['updated_time'], unique=False)

    op.create_table('trace_quota',
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reference', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_trace_quota'))
    )
    with op.batch_alter_table('trace_quota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_quota_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_quota_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_quota_updated_time'), ['updated_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_quota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_quota_updated_time'))
        batch_op.drop_index(batch_op.f('ix_trace_quota_reference'))
        batch_op.drop_index(batch_op.f('ix_trace_quota_created_time'))

    op.drop_table('trace_quota')
    with op.batch_alter_table('finance_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_price_updated_time'))
        batch_op.drop_index(batch_op.f('ix_finance_price_reference'))
        batch_op.drop_index(batch_op.f('ix_finance_price_created_time'))

    op.drop_table('finance_price')
    # ### end Alembic commands ###
